###raiz da aplicação
GET http://localhost:5181

###cadastrar aluno
POST http://localhost:5181/api/aluno/cadastrar
Content-Type: application/json

{
    "Nome": "Carlos",
    "DataNasimento": "1990-04-20"
}

###listar aluno
GET http://localhost:5181/api/aluno/listar
Content-Type: application/json

### Cadastrar um novo IMC
POST http://localhost:5181/api/imc/cadastrar
Content-Type: application/json

{
    "AlunoId": 4,
    "Altura": 1.88,
    "Peso": 98
}

###listar iMCS  
GET http://localhost:5181/api/imc/listar
Content-Type: application/json

### Alterar IMC
PUT http://localhost:5181/api/imc/atualizar
Content-Type: application/json

{
    "AlunoId": 2,
    "Altura": 1.90,
    "Peso": 70
}